export const DESSuites = {
  desfull: [
    './src/features/des/dashboard/dashboard-test.feature',
    './src/features/des/testCentre/testcentreJournalToday.feature',
    './src/features/des/testCentre/testcentreJournalTomorrow.feature',
    './src/features/des/testCentre/testcentreExaminerAccount.feature',
    './src/features/des/journal/JournalWithNoTests.feature',
    './src/features/des/cat-b/SuccessfulTests/SuccessfulTestWith0Faults.feature',
    './src/features/des/cat-b/SuccessfulTests/SuccessfulTestWith15Faults.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWith16Faults.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithSeriousFaults.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithEyesight.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithDangerousFault.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestswithCode4.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestswithCode21.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestWaitingRoomDeclaration.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestswithCode5.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestsByReturnToTestReport.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestsWaitingRoomToCar.feature',
    '.src/features/des/cat-b/TerminatedTests/TerminatedTestsRekey.feature',
    './src/features/des/cat-c/SuccessfulTests/SuccessfulTestWith10Faults.feature',
    './src/features/des/cat-c/UnsuccessfulTests/UnsuccessfulTestWithMultipleFaults.feature',
    './src/features/des/cat-cm/SuccessfulTestCatCM.feature',
    './src/features/des/cat-cm/UnsuccessfulTestCatCM.feature',
    './src/features//des/cat-b/SuccessfulTests/SuccessfulTestRekey.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestRekey.feature',
    './src/features/des/cat-d/UnsuccessfulTest.feature',
    './src/features/des/cat-d/SuccessfulTestWith10Faults.feature',
  ],
  successfultests: [
    './src/features/des/cat-b/SuccessfulTests/SuccessfulTestWith0Faults.feature',
    './src/features/des/cat-b/SuccessfulTests/SuccessfulTestWith15Faults.feature',
    './src/features/des/cat-c/SuccessfulTests/SuccessfulTestWith10Faults.feature',
    './src/features/des/cat-b/SuccessfulTests/SuccessfulTestRekey.feature',
    './src/features/des/cat-cm/SuccessfulTestCatCM.feature',
  ],
  unsuccessfultests: [
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWith16Faults.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithSeriousFaults.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithEyesight.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithDangerousFault.feature',
    './src/features/des/cat-c/UnsuccessfulTests/UnsuccessfulTestWithMultipleFaults.feature',
    './src/features/des/cat-cm/UnsuccessfulTestCatCM.feature',
    './src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestRekey.feature',
  ],
  terminatedtests: [
    './src/features/des/cat-b/TerminatedTests/TerminatedTestswithCode4.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestswithCode21.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestWaitingRoomDeclaration.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestswithCode5.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestsByReturnToTestReport.feature',
    './src/features/des/cat-b/TerminatedTests/TerminatedTestsWaitingRoomToCar.feature',
    '.src/features/des/cat-b/TerminatedTests/TerminatedTestsRekey.feature',
  ],
};
