"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const cucumber_1 = require("@cucumber/cucumber");
const completeUnsuccessfullOfficePage_1 = __importDefault(require("src/app-actions/des-action/completeUnsuccessfullOfficePage"));
const completeWaitingRoomFailEyesightToCarPage_1 = __importDefault(require("src/app-actions/des-action/completeWaitingRoomFailEyesightToCarPage"));
const completeRekeyReasonPage_1 = __importDefault(require("src/app-actions/des-action/completeRekeyReasonPage"));
const completeNonPassedFinalOutcomePage_1 = __importDefault(require("../../app-actions/des-action/completeNonPassedFinalOutcomePage"));
const desLoginAsUser_1 = __importDefault(require("../../app-actions/des-action/desLoginAsUser"));
const completeDeclarationPage_1 = __importDefault(require("../../app-actions/des-action/completeDeclarationPage"));
const completeComunicationPage_1 = __importDefault(require("../../app-actions/des-action/completeComunicationPage"));
const clickCompetencyButton_1 = __importDefault(require("../../app-actions/des-action/clickCompetencyButton"));
const completePassedFinalOutcomePage_1 = __importDefault(require("../../app-actions/des-action/completePassedFinalOutcomePage"));
const completeHealthDeclarationPage_1 = __importDefault(require("../../app-actions/des-action/completeHealthDeclarationPage"));
const checkConfirmationPageDetails_1 = __importDefault(require("../../app-actions/des-action/checkConfirmationPageDetails"));
const completeOfficePage_1 = __importDefault(require("../../app-actions/des-action/completeOfficePage"));
const completeCatCLegalRequirements_1 = __importDefault(require("../../app-actions/des-action/completeCatCLegalRequirements"));
const completeLegalRequirements_1 = __importDefault(require("../../app-actions/des-action/completeLegalRequirements"));
const addingFault_1 = __importDefault(require("../../app-actions/des-action/addingFault"));
const checkCorrectFaults_1 = __importDefault(require("../../app-actions/des-action/checkCorrectFaults"));
const completeCatCDeclarationPage_1 = __importDefault(require("../../app-actions/des-action/completeCatCDeclarationPage"));
const changeDayCheckDate_1 = __importDefault(require("../../app-actions/des-action/changeDayCheckDate"));
const completeWaitingRoomToCarPageDataTable_1 = __importDefault(require("../../app-actions/des-action/completeWaitingRoomToCarPageDataTable"));
const startTest_1 = __importDefault(require("../../app-actions/des-action/startTest"));
const logOut_1 = __importDefault(require("../../app-actions/des-action/logOut"));
const studentOptionADI3_1 = __importDefault(require("../../app-actions/des-action/studentOptionADI3"));
const lessonOptionADI3_1 = __importDefault(require("../../app-actions/des-action/lessonOptionADI3"));
const testReportADI3Questions_1 = __importDefault(require("../../app-actions/des-action/testReportADI3Questions"));
const keyboardClickLetter_1 = __importDefault(require("../../app-actions/des-action/keyboardClickLetter"));
(0, cucumber_1.When)(/^I am signed in as a random "([^"]*)?" user$/, desLoginAsUser_1.default);
(0, cucumber_1.When)(/^I complete the waiting room declaration page( for a category "([^"]*)?")?$/, completeDeclarationPage_1.default);
(0, cucumber_1.When)(/^I complete the waiting room for vocational declaration page$/, completeCatCDeclarationPage_1.default);
(0, cucumber_1.When)(/^I complete the waiting room communication page$/, completeComunicationPage_1.default);
(0, cucumber_1.When)(/^I complete the waiting room to car page from a data table for a category "([^"]*)?"$/, completeWaitingRoomToCarPageDataTable_1.default);
(0, cucumber_1.When)(/^I complete the waiting room to car page with fail eyesight$/, completeWaitingRoomFailEyesightToCarPage_1.default);
(0, cucumber_1.When)(/^I click the competency button "([^"]*)?"$/, clickCompetencyButton_1.default);
(0, cucumber_1.When)(/^I complete the successful final outcome screen from a data table$/, completePassedFinalOutcomePage_1.default);
(0, cucumber_1.When)(/^I complete the (unsuccessful|terminated) final outcome screen from a data table$/, completeNonPassedFinalOutcomePage_1.default);
(0, cucumber_1.When)(/^I complete the health declaration page for a category "([^"]*)?"$/, completeHealthDeclarationPage_1.default);
(0, cucumber_1.When)(/^I check the confirmation page details from a data table$/, checkConfirmationPageDetails_1.default);
(0, cucumber_1.When)(/^I complete the Office page from a data table$/, completeOfficePage_1.default);
(0, cucumber_1.When)(/^I complete the Office unsuccessful page from a data table$/, completeUnsuccessfullOfficePage_1.default);
(0, cucumber_1.When)(/^I select all legal requirements for a category "([^"]*)?"$/, completeLegalRequirements_1.default);
(0, cucumber_1.When)(/^I select all legal requirements Cat C$/, completeCatCLegalRequirements_1.default);
(0, cucumber_1.When)(/^I add "([^"]*)?" (driving|serious|dangerous) fault(s)? to the "([^"]*)?" field$/, addingFault_1.default);
(0, cucumber_1.When)(/^I check from a data table the number of faults are correct/, checkCorrectFaults_1.default);
(0, cucumber_1.When)(/^I go (back|forward) ([\d]+) day and check the date is correct$/, changeDayCheckDate_1.default);
(0, cucumber_1.When)(/^I complete the Rekey reason page from a data table$/, completeRekeyReasonPage_1.default);
(0, cucumber_1.When)(/^I start the test for "([^"]*)?"$/, startTest_1.default);
(0, cucumber_1.When)(/^I sign out$/, { timeout: 120000 }, logOut_1.default);
(0, cucumber_1.When)(/^I select the student option "([^"]*)?"$/, studentOptionADI3_1.default);
(0, cucumber_1.When)(/^I select the lesson theme options$/, lessonOptionADI3_1.default);
(0, cucumber_1.When)(/^I score (\d+) for the (\d+)(st|nd|rd|th) question for section "([^"]*)?"$/, testReportADI3Questions_1.default);
(0, cucumber_1.When)(/^I input the letter "([^"]*)?" into adi3 review textbox$/, keyboardClickLetter_1.default);
